platform :ios, '13.0'
use_frameworks!

target 'StoryCameraPlugin' do
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
end
